spring:
  profiles:
    active: pro
server:
  port: 8080
logging:
  config: classpath:logback/logback-spring-${spring.profiles.active}.xml
---
spring:
  config:
    activate:
      on-profile: local
thread:
  count: 5
---
spring:
  config:
    activate:
      on-profile: pro
thread:
  count: 2
